### ISSUE TITLE
Invalid numbers are recognized

### ISSUE THREAD

**Issue by intrueder** [anna41/task_for_kottans#3]
Numbers `41111111111111112`, `3434343434343433`, `50000000000006114` do no pass validation (correct) and should not be recognized, but they are.

**Comment by anna41** [comment]
Fixed

**Comment by intrueder** [comment]
Still reproducable.
Pass `3434343434343433` (invalid number according to Luhn) to `GetCreditCardVendor`
Expected result: "Unknown"
Actual result: "American Express"

**Comment by anna41** [comment]
Fixed

**Comment by intrueder** [comment]
Still reproducable for `50000000000006114`

**Comment by anna41** [comment]
Fixed

**Comment by intrueder** [comment]
Still reproducable.
Pass `50000000000006114` (invalid number according to Luhn) to `GetCreditCardVendor`
Expected result: "Unknown"
Actual result: "Maestro"

**Comment by anna41** [comment]
this number start from 50 and have length = 17, it's good for maestro,isn't?

**Comment by intrueder** [comment]
It will be good for Maestro, when it will pass Luhn validation :)

**Comment by anna41** [comment]
I have this result.It's bad?
![2](https://cloud.githubusercontent.com/assets/19194015/15099223/8193becc-1558-11e6-9723-e01c2f6c3a32.JPG)

**Comment by intrueder** [comment]
Not bad, but you need to fix `GetCreditCardVendor` method to make it process only valid card numbers.

**Comment by anna41** [comment]
Fixed
